apiVersion: lestak.sh/v1alpha1
kind: VaultSecretSync
metadata:
  name: database-credentials-sync
  namespace: apps
spec:
  source:
    vault:
      address: "https://vault.example.com:8200"
      authMethod: "kubernetes"
      role: "app-secret-sync"
      # Database credentials in Vault
      path: "secret/data/databases/postgres"

  destinations:
    - gcp:
        project: "my-app-project"
        name: "postgres-credentials"
        replicationLocations:
          - "us-central1"
        labels:
          app: "postgresql"
          env: "staging"

---
apiVersion: lestak.sh/v1alpha1
kind: VaultSecretSync
metadata:
  name: api-keys-sync
  namespace: apps
spec:
  source:
    vault:
      address: "https://vault.example.com:8200"
      authMethod: "kubernetes"
      role: "app-secret-sync"
      # API keys in Vault
      path: "secret/data/api-keys/external"

  destinations:
    - gcp:
        project: "my-app-project"
        name: "external-api-keys"
        replicationLocations:
          - "us-central1"
        labels:
          app: "api-gateway"
          env: "staging"

---
apiVersion: lestak.sh/v1alpha1
kind: VaultSecretSync
metadata:
  name: certificates-sync
  namespace: apps
spec:
  source:
    vault:
      address: "https://vault.example.com:8200"
      authMethod: "kubernetes"
      role: "app-secret-sync"
      # TLS certificates in Vault
      path: "secret/data/certificates/tls"

  destinations:
    - gcp:
        project: "my-app-project"
        name: "tls-certificates"
        replicationLocations:
          - "us-central1"
          - "us-east1"
        labels:
          type: "certificate"
          env: "staging"

  # Only sync certificate-related keys
  transforms:
    include:
      - "^cert$"
      - "^key$"
      - "^ca$"
