apiVersion: lestak.sh/v1alpha1
kind: VaultSecretSync
metadata:
  name: vault-to-gcp-example
  namespace: default
spec:
  # Source: HashiCorp Vault configuration
  source:
    vault:
      # Vault server address
      address: "https://vault.example.com:8200"
      # Vault namespace (optional, for Vault Enterprise)
      namespace: "admin"
      # Authentication method (kubernetes, token, etc.)
      authMethod: "kubernetes"
      # Role for Kubernetes authentication
      role: "vault-secret-sync"
      # Path to the secret in Vault (KV v2 format)
      path: "secret/data/myapp/database"
      # TTL for the Vault token (optional)
      ttl: "1h"

  # Destination: GCP Secret Manager configuration
  destinations:
    - gcp:
        # GCP Project ID where secrets will be stored
        project: "my-gcp-project-id"
        # Secret name in GCP Secret Manager
        # The path will be transformed: secret/data/myapp/database -> myapp-database
        name: "myapp-database"
        # Replication locations for the secret
        replicationLocations:
          - "us-central1"
          - "us-east1"
        # Labels to apply to the secret in GCP
        labels:
          environment: "production"
          application: "myapp"
          managed-by: "vault-secret-sync"

  # Sync behavior configuration
  syncConfig:
    # Automatically sync on Vault events (create, update, delete)
    autoSync: true
    # Sync interval (if autoSync is false, periodic sync)
    syncInterval: "5m"
    # Delete secret in GCP when deleted from Vault
    deleteOnRemove: true

  # Optional: Notifications on sync events
  notifications:
    - slack:
        # Slack webhook URL (can also use urlSecret)
        url: "https://hooks.slack.com/services/YOUR/WEBHOOK/URL"
        # Events to notify on
        events:
          - "sync.success"
          - "sync.failure"
        # Custom message body
        body: "Secret {{.VaultSecretSync.Name}} sync {{.Event}}"

    - email:
        # SMTP configuration
        host: "smtp.gmail.com"
        port: 587
        username: "alerts@example.com"
        password: "your-password"
        from: "vault-sync@example.com"
        to: "devops@example.com"
        subject: "Vault Secret Sync Alert"
        events:
          - "sync.failure"
        # TLS configuration
        insecureSkipVerify: false

  # Optional: Transform secrets before syncing
  transforms:
    # Include only specific keys
    include:
      - "^database_.*"
      - "^api_key$"
    # Exclude specific keys
    exclude:
      - ".*_internal$"
    # Template to transform the secret data
    template: |
      {
        {{- range $key, $value := . }}
        "{{ $key }}": "{{ $value }}"{{ if not (last) }},{{ end }}
        {{- end }}
      }

  # Optional: Dry run mode (log actions without making changes)
  dryRun: false

  # Optional: Suspend syncing
  suspend: false
